export const queryKeys = {
  health: ['health'],
  me: (userId) => ['auth', 'me', userId],
  platformUsers: () => ['platform', 'users'],
  userTenants: (userId) => ['users', userId, 'tenants'],
  tenant: (tenantId) => ['tenants', tenantId],
  tenantUsers: (tenantId) => ['tenants', tenantId, 'users'],
  knowledge: (tenantId) => ['tenants', tenantId, 'knowledge'],
  knowledgeDocument: (tenantId, documentId) => [
    'tenants',
    tenantId,
    'knowledge',
    documentId,
  ],
  knowledgeSearch: (tenantId, query, limit) => [
    'tenants',
    tenantId,
    'knowledge',
    'search',
    query,
    limit,
  ],
  intelligenceQuery: (tenantId, query, limit) => [
    'tenants',
    tenantId,
    'intelligence',
    'query',
    query,
    limit,
  ],
  skills: (tenantId) => ['tenants', tenantId, 'skills'],
  skill: (tenantId, skillId) => ['tenants', tenantId, 'skills', skillId],
  tools: (tenantId) => ['tenants', tenantId, 'tools'],
  connectors: (tenantId) => ['tenants', tenantId, 'connectors'],
  webhookEvents: (tenantId) => ['tenants', tenantId, 'webhooks', 'events'],
  observabilityTenant: (tenantId, hours) => [
    'tenants',
    tenantId,
    'observability',
    'usage-summary',
    hours,
  ],
  observabilityPlatform: () => ['observability', 'platform', 'summary'],
  healthComponents: () => ['observability', 'health'],
  approvals: (tenantId) => ['tenants', tenantId, 'approvals'],
  approval: (tenantId, approvalId) => [
    'tenants',
    tenantId,
    'approvals',
    approvalId,
  ],
}

export default queryKeys
